[package]
name = "weather"
version = "0.1.0"
authors = ["michal"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12.0"
attohttpc = "0.16.3"
prettytable-rs = "0.8.0"
